
<!DOCTYPE HTML>

<html lang="en" class="_theme-default">

<head>
  <meta charset="utf-8">
  <title>Std&#58;&#58;uncaught_exception - C++ - W3cubDocs</title>
  
  <meta name="description" content="Sometimes it&#39;s safe to throw an exception even while std&#58;&#58;uncaught_exception() &#61;&#61; true. For example, if stack unwinding causes &hellip;">
  <meta name="keywords" content="std, uncaught, exception, exceptions, c++, cpp">
  <meta name="HandheldFriendly" content="True">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  
  <link rel="canonical" href="https://docs.w3cub.com/cpp/error/uncaught_exception.html">
  <link href="/favicon.png" rel="icon">
  <link rel="stylesheet" type="text/css" href="/assets/application-9c7b0d969c0ce639a6c01c2badcdd81667c7c66206aa3d0fccc5cb0585fb1b912dab72ea882101d18010680927514b4b77b107282db8f756fbf63301fe9c88b0.css">
  <script type="text/javascript" src="/assets/application-79c555f6b25481fffac2cac30a7f3e54e608ca09e9e8e42bb1790095ba6d0fcace47d6bc624ddce952c70370892f2d46864f89e6943d4f7f7ff16c8a3231a91a.js"></script>
  <script src="/json/cpp.js"></script>
  
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-R3WC07G3GB"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-R3WC07G3GB');
</script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2572770204602497"
     crossorigin="anonymous"></script>
<script async custom-element="amp-auto-ads"
  src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
</script>


</head>

<body class="docs">
	<amp-auto-ads type="adsense"
              data-ad-client="ca-pub-2572770204602497">
	</amp-auto-ads>
	<div class="_app">
	<header class="_header">

  <a class="_home-link" href="/" ></a>
  <a class="_menu-link"></a>
  <h1 class="_logo">
    <a href="/" class="_nav-link" title="API Documentation Browser">W3cubDocs</a>
  </h1>
  
  <span class="_logo-sub-nav">/</span><span class="_logo-sub-nav"><a href="/cpp/" class="_nav-link" title="" style="margin-left:0;">C++</a></span>
  
  <nav class="_nav">
    <a href="https://tools.w3cub.com/?_sp=docs" target="_blank" class="_nav-link ">W3cubTools</a>
    <a href="/cheatsheets/" class="_nav-link ">Cheatsheets</a>
    <a href="/about/" class="_nav-link ">About</a>
  </nav>
</header>
	<section class="_sidebar">
		
		<form class="_search">
		  <input type="search" class="_search-input" placeholder="Search&hellip;" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="20">
		  <a class="_search-clear"></a>
		  <div class="_search-tag"></div>
		</form>
		
		<div class="_list-wrap">
			<div class="_list">
			
			</div>
		</div>
	</section>
	<section class="_container ">
		<div class="_content">
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="6861657091"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
			<div class="_page _cppref">
				
				
<h1 id="firstHeading" class="firstHeading">std::uncaught_exception, std::uncaught_exceptions</h1>            <table class="t-dcl-begin"> <tr class="t-dsc-header"> <th> Defined in header <code><a href="../header/exception" title="cpp/header/exception">&lt;exception&gt;</a></code> </th> <th> </th> <th> </th> </tr>  <tr class="t-dcl-rev-aux"> <td></td> <td rowspan="3">(1)</td> <td></td> </tr> <tr class="t-dcl t-until-cxx11"> <td> <pre data-language="cpp">bool uncaught_exception() throw();</pre>
</td>  <td> <span class="t-mark-rev t-until-cxx11">(until C++11)</span> </td> </tr> <tr class="t-dcl t-since-cxx11 t-until-cxx20"> <td> <pre data-language="cpp">bool uncaught_exception() noexcept;</pre>
</td>  <td> <span class="t-mark-rev t-since-cxx11">(since C++11)</span> <br><span class="t-mark">(deprecated in C++17)</span> <br><span class="t-mark-rev t-until-cxx20">(removed in C++20)</span> </td> </tr>  <tr class="t-dcl t-since-cxx17"> <td> <pre data-language="cpp">int uncaught_exceptions() noexcept;</pre>
</td> <td> (2) </td> <td> <span class="t-mark-rev t-since-cxx17">(since C++17)</span> </td> </tr>  </table> <div class="t-li1">
<span class="t-li">1)</span> Detects if the current thread has a live exception object, that is, an exception has been thrown or rethrown and not yet entered a matching catch clause, <code><a href="terminate" title="cpp/error/terminate">std::terminate</a></code> or <code><a href="unexpected" title="cpp/error/unexpected">std::unexpected</a></code>. In other words, <code>std::uncaught_exception</code> detects if <a href="../language/throw#Stack_unwinding" title="cpp/language/throw">stack unwinding</a> is currently in progress.</div> <div class="t-li1">
<span class="t-li">2)</span> Detects how many exceptions in the current thread have been thrown or rethrown and not yet entered their matching catch clauses. </div> <p>Sometimes it's safe to throw an exception even while <code>std::uncaught_exception() == true</code>. For example, if <a href="../language/throw#Stack_unwinding" title="cpp/language/throw">stack unwinding</a> causes an object to be destructed, the destructor for that object could run code that throws an exception as long as the exception is caught by some catch block before escaping the destructor.</p>
<h3 id="Parameters"> Parameters</h3> <p>(none).</p>
<h3 id="Return_value"> Return value</h3> <div class="t-li1">
<span class="t-li">1)</span> <code>true</code> if stack unwinding is currently in progress in this thread, <code>false</code> otherwise.</div> <div class="t-li1">
<span class="t-li">2)</span> The number of uncaught exception objects in the current thread.</div> <h3 id="Notes"> Notes</h3> <p>An example where int-returning <code>uncaught_exceptions</code> is used is the <a rel="nofollow" class="external text" href="https://www.boost.org/doc/libs/release/libs/log/doc/html/index.html">boost.log</a> library: the expression <code>BOOST_LOG(logger) &lt;&lt; foo();</code> first creates a guard object and records the number of uncaught exceptions in its constructor. The output is performed by the guard object's destructor unless <code>foo()</code> throws (in which case the number of uncaught exceptions in the destructor is greater than what the constructor observed).</p>
<p><a href="https://en.cppreference.com/w/cpp/experimental/scope_fail" title="cpp/experimental/scope fail"><code>std::experimental::scope_fail</code></a> and <a href="https://en.cppreference.com/w/cpp/experimental/scope_success" title="cpp/experimental/scope success"><code>std::experimental::scope_success</code></a> in LFTS v3 rely on the functionality of <code>uncaught_exceptions</code>, because their destructors need to do different things that depend on whether is called during stack unwinding.</p>
<table class="wikitable ftm-begin ftm-has-value"> <tr> <th>
<a href="../utility/feature_test" title="cpp/utility/feature test">Feature-test</a> macro</th> <th>Value</th> <th><span title="Standard in which the feature is introduced">Std</span></th> <th>Comment </th>
</tr> <tr> <td><a href="../feature_test#Library_features" title="cpp/feature test"><code>__cpp_lib_uncaught_exceptions</code></a></td> <td><span class="nu0">201411L</span></td> <td><span class="t-mark">(C++17)</span></td> <td>
<a href="#Top"><code>std::uncaught_exceptions</code></a> </td>
</tr>
</table> <h3 id="Example"> Example</h3> <div class="t-example"> <div class="cpp source-cpp"><pre data-language="cpp">#include &lt;exception&gt;
#include &lt;iostream&gt;
#include &lt;stdexcept&gt;
 
struct Foo
{
    char id{'?'};
    int count = std::uncaught_exceptions();
 
    ~Foo()
    {
        count == std::uncaught_exceptions()
            ? std::cout &lt;&lt; id &lt;&lt; ".~Foo() called normally\n"
            : std::cout &lt;&lt; id &lt;&lt; ".~Foo() called during stack unwinding\n";
    }
};
 
int main()
{
    Foo f{'f'};
 
    try
    {
        Foo g{'g'};
        std::cout &lt;&lt; "Exception thrown\n";
        throw std::runtime_error("test exception");
    }
    catch (const std::exception&amp; e)
    {
        std::cout &lt;&lt; "Exception caught: " &lt;&lt; e.what() &lt;&lt; '\n';
    }
}</pre></div> <p>Possible output:</p>
<div class="text source-text"><pre data-language="c">Exception thrown
g.~Foo() called during stack unwinding
Exception caught: test exception
f.~Foo() called normally</pre></div> </div> <h3 id="Defect_reports"> Defect reports</h3> <p>The following behavior-changing defect reports were applied retroactively to previously published C++ standards.</p>
<table class="dsctable"> <tr> <th> DR </th> <th> Applied to </th> <th> Behavior as published </th> <th> Correct behavior </th>
</tr> <tr> <td> <a rel="nofollow" class="external text" href="https://cplusplus.github.io/LWG/issue70">LWG 70</a> </td> <td> C++98 </td> <td> the exception specification of <code>uncaught_exception()</code> was missing </td> <td> specified as <code>throw()</code> </td>
</tr>
</table> <h3 id="See_also"> See also</h3> <table class="t-dsc-begin"> <tr class="t-dsc"> <td> <div><a href="terminate" title="cpp/error/terminate"> <span class="t-lines"><span>terminate</span></span></a></div> </td> <td> function called when exception handling fails <br> <span class="t-mark">(function)</span>  </td>
</tr> <tr class="t-dsc"> <td> <div><a href="exception_ptr" title="cpp/error/exception ptr"> <span class="t-lines"><span>exception_ptr</span></span></a></div>
<div><span class="t-lines"><span><span class="t-mark-rev t-since-cxx11">(C++11)</span></span></span></div> </td> <td> shared pointer type for handling exception objects <br> <span class="t-mark">(typedef)</span>  </td>
</tr> <tr class="t-dsc"> <td> <div><a href="current_exception" title="cpp/error/current exception"> <span class="t-lines"><span>current_exception</span></span></a></div>
<div><span class="t-lines"><span><span class="t-mark-rev t-since-cxx11">(C++11)</span></span></span></div> </td> <td> captures the current exception in a <code><a href="exception_ptr" title="cpp/error/exception ptr">std::exception_ptr</a></code> <br> <span class="t-mark">(function)</span>  </td>
</tr> </table> <h3 id="External_links"> External links</h3> <table> <tr style="vertical-align:top;"> <td>1. </td> <td>
<a rel="nofollow" class="external text" href="http://www.gotw.ca/gotw/047.htm">GOTW issue 47: Uncaught Exceptions</a> </td>
</tr> <tr style="vertical-align:top;"> <td>2. </td> <td>
<a rel="nofollow" class="external text" href="https://wg21.link/n4152">Rationale for <code>std::uncaught_exceptions</code></a> (N4125) </td>
</tr>
</table>           <div class="_attribution">
  <p class="_attribution-p">
    © cppreference.com<br>Licensed under the Creative Commons Attribution-ShareAlike Unported License v3.0.<br>
    <a href="https://en.cppreference.com/w/cpp/error/uncaught_exception" class="_attribution-link">https://en.cppreference.com/w/cpp/error/uncaught_exception</a>
  </p>
</div>

				
			</div>
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="1992473792"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
		</div>
	</section>

	</div>
	<svg style="display:none">
		<symbol id="icon-dir"><svg viewBox="0 0 20 20"><path d="M15 10c0 .3-.305.515-.305.515l-8.56 5.303c-.625.41-1.135.106-1.135-.67V4.853c0-.777.51-1.078 1.135-.67l8.56 5.305S15 9.702 15 10z"/></svg></symbol>
	  </svg>
</body>
</html>
