
<!DOCTYPE HTML>

<html lang="en" class="_theme-default">

<head>
  <meta charset="utf-8">
  <title>Std&#58;&#58;promise&#58;&#58;set_exception - C++ - W3cubDocs</title>
  
  <meta name="description" content=" Atomically stores the exception pointer p into the shared state and makes the state ready. ">
  <meta name="keywords" content="std, promise, r, set, exception, c++, cpp">
  <meta name="HandheldFriendly" content="True">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="mobile-web-app-capable" content="yes">
  
  <link rel="canonical" href="https://docs.w3cub.com/cpp/thread/promise/set_exception.html">
  <link href="/favicon.png" rel="icon">
  <link rel="stylesheet" type="text/css" href="/assets/application-9c7b0d969c0ce639a6c01c2badcdd81667c7c66206aa3d0fccc5cb0585fb1b912dab72ea882101d18010680927514b4b77b107282db8f756fbf63301fe9c88b0.css">
  <script type="text/javascript" src="/assets/application-79c555f6b25481fffac2cac30a7f3e54e608ca09e9e8e42bb1790095ba6d0fcace47d6bc624ddce952c70370892f2d46864f89e6943d4f7f7ff16c8a3231a91a.js"></script>
  <script src="/json/cpp.js"></script>
  
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-R3WC07G3GB"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-R3WC07G3GB');
</script>
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2572770204602497"
     crossorigin="anonymous"></script>
<script async custom-element="amp-auto-ads"
  src="https://cdn.ampproject.org/v0/amp-auto-ads-0.1.js">
</script>


</head>

<body class="docs">
	<amp-auto-ads type="adsense"
              data-ad-client="ca-pub-2572770204602497">
	</amp-auto-ads>
	<div class="_app">
	<header class="_header">

  <a class="_home-link" href="/" ></a>
  <a class="_menu-link"></a>
  <h1 class="_logo">
    <a href="/" class="_nav-link" title="API Documentation Browser">W3cubDocs</a>
  </h1>
  
  <span class="_logo-sub-nav">/</span><span class="_logo-sub-nav"><a href="/cpp/" class="_nav-link" title="" style="margin-left:0;">C++</a></span>
  
  <nav class="_nav">
    <a href="https://tools.w3cub.com/?_sp=docs" target="_blank" class="_nav-link ">W3cubTools</a>
    <a href="/cheatsheets/" class="_nav-link ">Cheatsheets</a>
    <a href="/about/" class="_nav-link ">About</a>
  </nav>
</header>
	<section class="_sidebar">
		
		<form class="_search">
		  <input type="search" class="_search-input" placeholder="Search&hellip;" autocomplete="off" autocapitalize="off" autocorrect="off" spellcheck="false" maxlength="20">
		  <a class="_search-clear"></a>
		  <div class="_search-tag"></div>
		</form>
		
		<div class="_list-wrap">
			<div class="_list">
			
			</div>
		</div>
	</section>
	<section class="_container ">
		<div class="_content">
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="6861657091"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
			<div class="_page _cppref">
				
				
<h1 id="firstHeading" class="firstHeading">std::promise&lt;R&gt;::set_exception</h1>            <table class="t-dcl-begin"> <tr class="t-dcl t-since-cxx11"> <td> <pre data-language="cpp">void set_exception( std::exception_ptr p );</pre>
</td> <td class="t-dcl-nopad"> </td> <td> <span class="t-mark-rev t-since-cxx11">(since C++11)</span> </td> </tr>  </table> <p>Atomically stores the exception pointer <code>p</code> into the shared state and makes the state ready.</p>
<p>The operation behaves as though <code><a href="set_value" title="cpp/thread/promise/set value">set_value</a></code>, <code>set_exception</code>, <code><a href="set_value_at_thread_exit" title="cpp/thread/promise/set value at thread exit">set_value_at_thread_exit</a></code>, and <code><a href="set_exception_at_thread_exit" title="cpp/thread/promise/set exception at thread exit">set_exception_at_thread_exit</a></code> acquire a single mutex associated with the promise object while updating the promise object.</p>
<p>An exception is thrown if there is no shared state or the shared state already stores a value or exception.</p>
<p>Calls to this function do not introduce data races with calls to <code><a href="get_future" title="cpp/thread/promise/get future">get_future</a></code> (therefore they need not synchronize with each other).</p>
<h3 id="Parameters"> Parameters</h3> <table class="t-par-begin"> <tr class="t-par"> <td> p </td> <td> - </td> <td> exception pointer to store. The behavior is undefined if <code>p</code> is null. </td>
</tr>
</table> <h3 id="Return_value"> Return value</h3> <p>(none).</p>
<h3 id="Exceptions"> Exceptions</h3> <p><code><a href="../future_error" title="cpp/thread/future error">std::future_error</a></code> on the following conditions:</p>
<ul>
<li> <code>*this</code> has no shared state. The error code is set to <a href="../future_errc" title="cpp/thread/future errc"><code>no_state</code></a>. </li>
<li> The shared state already stores a value or exception. The error code is set to <a href="../future_errc" title="cpp/thread/future errc"><code>promise_already_satisfied</code></a>. </li>
</ul>  <h3 id="Example"> Example</h3> <div class="t-example"> <div class="cpp source-cpp"><pre data-language="cpp">#include &lt;thread&gt;
#include &lt;iostream&gt;
#include &lt;future&gt;
 
int main()
{
    std::promise&lt;int&gt; p;
    std::future&lt;int&gt; f = p.get_future();
 
    std::thread t([&amp;p]{
        try {
            // code that may throw
            throw std::runtime_error("Example");
        } catch(...) {
            try {
                // store anything thrown in the promise
                p.set_exception(std::current_exception());
                // or throw a custom exception instead
                // p.set_exception(std::make_exception_ptr(MyException("mine")));
            } catch(...) {} // set_exception() may throw too
        }
    });
 
    try {
        std::cout &lt;&lt; f.get();
    } catch(const std::exception&amp; e) {
        std::cout &lt;&lt; "Exception from the thread: " &lt;&lt; e.what() &lt;&lt; '\n';
    }
    t.join();
}</pre></div> <p>Output:</p>
<div class="text source-text"><pre data-language="c">Exception from the thread: Example</pre></div> </div> <h3 id="See_also"> See also</h3> <table class="t-dsc-begin"> <tr class="t-dsc"> <td> <div><a href="set_exception_at_thread_exit" title="cpp/thread/promise/set exception at thread exit"> <span class="t-lines"><span>set_exception_at_thread_exit</span></span></a></div> </td> <td> sets the result to indicate an exception while delivering the notification only at thread exit <br> <span class="t-mark">(public member function)</span>  </td>
</tr> </table>           <div class="_attribution">
  <p class="_attribution-p">
    Â© cppreference.com<br>Licensed under the Creative Commons Attribution-ShareAlike Unported License v3.0.<br>
    <a href="https://en.cppreference.com/w/cpp/thread/promise/set_exception" class="_attribution-link">https://en.cppreference.com/w/cpp/thread/promise/set_exception</a>
  </p>
</div>

				
			</div>
			<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-2572770204602497"
     data-ad-slot="1992473792"
     data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script>
     (adsbygoogle = window.adsbygoogle || []).push({});
</script>
		</div>
	</section>

	</div>
	<svg style="display:none">
		<symbol id="icon-dir"><svg viewBox="0 0 20 20"><path d="M15 10c0 .3-.305.515-.305.515l-8.56 5.303c-.625.41-1.135.106-1.135-.67V4.853c0-.777.51-1.078 1.135-.67l8.56 5.305S15 9.702 15 10z"/></svg></symbol>
	  </svg>
</body>
</html>
